version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql-container-local
    volumes:
      - ../data/mysql/datadir:/var/lib/mysql
      - ../data/mysql/conf/my.cnf:/etc/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
